# Generated by Django 4.2.3 on 2023-07-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('fechavencimiento', models.DateField(verbose_name='fecha')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('idcategoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='app.categoria', verbose_name='idcategoria')),
            ],
        ),
    ]
